ftp.mirror.ac.uk
ftpsearch.lycos.com
ftp.sunet.se
packetstormsecurity.com
slashdot.org
sunsite.org.uk
www.debian.org
www.freshmeat.net
www.linux.com
www.linux-mandrake.com
www.linux.org
www.linuxtoday.com
www.linuxworld.com
www.lwn.net
www.redhat.com
www.slashdot.org
www.suse.com
www.novell.com
ftp.novell.com
ftp.funet.fi
ftp.ntua.gr
